steps:
  - id: 'Build image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - -c
      - |
        make dev-build
          .
  - id: 'Run tests'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - -c
      - |
        make dev-test
    waitFor: ['Build image']

substitutions:
  _SERVICE_NAME: shuttle
  _BUILD_ID_SHORT: ${BUILD_ID:0:8}
  _DOCKER_TAG: ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/hubblehq-docker/${_SERVICE_NAME}

options:
  dynamicSubstitutions: true
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY